### ISSUE TITLE
brazilian portuguese?

### ISSUE THREAD

**Issue by matheusandradecrashb** [Level-Share-Square/SMC-translations#2]
note that the special letters (eg. á â ã) need to be added, but that was probably already done for spanish.

**Comment by matheusandradecrashb** [comment]
oh i noticed theres no spanish

**Comment by Luigibonus** [comment]
As of next Snapshot, there indeed are new special characters! The ones we've added are: ÁÀÄÂÉÈËÊÍÌÏÎÓÒÖÔÚÙÜÛáàäâéèëêíìïîóòöôúùüûÇçßẞ¡¿ÃãÕõÑñ

Feel free to post if you need any more, tho it may take some time to add the new characters.
