### ISSUE TITLE
How do i add the translation for smc?

### ISSUE THREAD

**Issue by Caicowisk** [Level-Share-Square/SMC-translations#21]
How do i add the translation for smc?

**Comment by Luigibonus** [comment]
Heya, the instructions on how to create a translation file can be found here (when scrolling down): https://github.com/Level-Share-Square/SMC-translations

Right below you can see how you can submit your translation file. This translation file isn't immediately added to the game yet, it is first reviewed for approval and if all is good, added to the next update of SMC.

If you have any questions with a particular step, feel free to ask here or on LSS!
