### ISSUE TITLE
I could make a Polish translation but...

### ISSUE THREAD

**Issue by ElCabanoss** [Level-Share-Square/SMC-translations#3]
I could make a Polish translation but I guess that Polish letters won't display in the game.
![yyy](https://github.com/Level-Share-Square/SMC-translations/assets/157318359/04bf8965-8d47-4745-956b-e8d82a70e4d7)

**Comment by Luigibonus** [comment]
If you could give us a list of Polish letters, I'll see if I could implement them

**Comment by Luigibonus** [comment]
Sorry, fat-fingerred on the close button

**Comment by ElCabanoss** [comment]
ą ć Ć ę ł Ł ń ó Ó ś Ś ż Ż ź Ź

Btw, is there any deadline?

**Comment by Luigibonus** [comment]
Nope! You can work on translations whenever you'd like.

**Comment by ElCabanoss** [comment]
Alright! :D 

So I shouldn't start translating until you implement the Polish letters, right?

**Comment by Luigibonus** [comment]
I checked out the letters, they should be simple enough to add so feel free to start!

**Comment by ElCabanoss** [comment]
Alr, I'll start tomorrow. I'm tired after work today.

**Comment by ElCabanoss** [comment]
OK, I've finished but apparently I can't upload the file because I need push access or something.

**Comment by ElCabanoss** [comment]
Done.
