### ISSUE TITLE
Japanese translation (if anyone can, please post it)

### ISSUE THREAD

**Issue by tyhomas** [Level-Share-Square/SMC-translations#7]

**Comment by Luigibonus** [comment]
Heya there. Are you Japanese and willing to start a Japanese translation, or are you simply requesting a Japanese translation to be added?

**Comment by tyhomas** [comment]
requesting a Japanese translation

**Comment by Luigibonus** [comment]
Unfortunately we don't have any Japanese translators at the current moment! It may be a possibility in the future though.

**Comment by tyhomas** [comment]
Then, why not try google translate?

**Comment by Luigibonus** [comment]
Google Translate unfortunately isn't always accurate and unbeknown to context that may be necessary for correct translations, so we prefer translations done by people.

**Comment by tyhomas** [comment]
Oh! I have an idea! Add the button named: if you are Japanese and want to add the Japanese language, click here!

**Comment by Luigibonus** [comment]
I do plan to put more info about community translations inside the next Snapshot, and Japanese people are free to submit translations whenever. Hope that clears it up - don't think there's anything else to add here, so I'm closing this issue.
